# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CosmicPi
email: info@cosmicpi.org
mailchimp: //cosmicpi.us16.list-manage.com/subscribe/post?u=667baca612d7fdc8725ff37a0&amp;id=dd513e0879 # //something.us7.list-manage.com/subscribe/post?u=1940bad1f5045336dde83154a&amp;id=fc69769541
description: > # this means to ignore newlines until "baseurl:"
  The Cosmic Pi project aims to build the world's largest open source
  distributed cosmic ray telescope. You can be a part of the project, by
  becoming a Cosmic Pixel!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: CosmicPi
github_username:  CosmicPi

disqus:
    shortname: cosmicpi

# Build settings
markdown: kramdown
#theme: jekyll-theme-hacker
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
